# Generated by Django 3.2.3 on 2021-05-19 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloomingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('selection', models.CharField(max_length=50, null=True)),
                ('doing', models.CharField(max_length=50, null=True)),
                ('feel', models.IntegerField(null=True)),
                ('tree_state', models.CharField(max_length=60, null=True)),
                ('tree_forward', models.CharField(max_length=50, null=True)),
                ('home_mood', models.CharField(max_length=50, null=True)),
                ('home_door', models.CharField(max_length=5, null=True)),
                ('last_q', models.CharField(max_length=80, null=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
